apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: website
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
      color: green
  template:
    metadata:
      labels:
        app: website
        color: green
    spec:
      containers:
        - name: orgpulse-green
          image: orgpulse:green
          ports:
            - containerPort: 80
